language: c

addons:
  apt:
    packages:
      - cmake
      - valgrind
      - lcov

before_script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake ../
  - make

jobs:
  include:
    - stage: tests
      name: "Check tests"
      script:
        - ./test

    - stage: coverage
      name: "Test coverage"
      script:
        - ./test
        - cd CMakeFiles/test.dir/tests
        - gcov tests.cpp.gcno
        - lcov --capture --directory ../../ --output-file tests.info
        - genhtml -o ../../../../coverage-report tests.info
        - cd ../../../

    - stage: memcheck
      name: "Memory check"
      script:
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./test

    - stage: static_analysis
      name: "Static analysis"
      script:
        - cd ..
        - ./cppcheck/cppcheck --enable=all --error-exitcode=1 --inconclusive include/* src/* tests/*

    - stage: linters
      name: "Linters"
      script:
        - python2.7 ../cpplint/cpplint.py --extensions=c include/* src/* tests/*
        - python2.7 ../cpplint/cpplint.py --extensions=c++ tests/*


