language: c

install:
  - pip install cpplint

addons:
  apt:
    packages:
      - cmake
      - valgrind
      - lcov
      - cppcheck

before_script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake ../
  - touch my_file
  - touch test_file
  - touch result
  - make

jobs:
  include:
    - stage: u-tests
      name: "Unit-tests"
      script:
        - ./u_test_dynamic
        - ./u_test_static

    - stage: coverage
      name: "Test coverage dynamic library"
      script:
        - ./u_test_dynamic
        - cd CMakeFiles/u_test_dynamic.dir/tests
        - gcov unit_tests_parallel.cpp.gcno
        - lcov --capture --directory ../../ --output-file unit_tests.info
        - genhtml -o ../../../../coverage-report unit_tests.info
        - cd ../../../

    - stage: stress_tests
      name: "Stress tests for libraries"
      script:
        - ./prog
        - ./stress_test_s
        - ./stress_test_d
        - ./stress_test_controller

    - stage: memcheck
      name: "Memory check"
      script:
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./u_test_dynamic
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./u_test_static
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./stress_test_s
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./stress_test_d
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./stress_test_controller

    - stage: static_analysis
      name: "Static analysis"
      script:
        - cd ..
        - cppcheck --enable=all --error-exitcode=1 --inconclusive include/* src/* tests/*

