language: cpp

before_script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug

jobs:
  include:
    - stage: build
      neme: "Build"
      script: ./cmake-build-debug/

    - stage: tests
      name: "CheckSpamTests"
      script: ./cmake-build-dedbug/test
