language: c

before_script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake ../
  - make

jobs:
  include:
    - stage: tests
      name: "CheckSpamTests"
      script:
        - ./test

    - stage: memcheck
      name: "Memory check"
      script:
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./test
