language: c

before_script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug

jobs:
  include:
    - stage: build
      neme: "Build"
      script:
        - cmake ../
        - make

    - stage: tests
      name: "CheckSpamTests"

      script:
        - cmake ../
        - make
        - ./test
